steer/Controllers/DocsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using steer.Models;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml;
using ClosedXML.Excel;
using System.Web;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using System.Data.Entity.Validation;
using System.Globalization;

namespace steer.Controllers
{
    public class DocsController : Controller
    {
        private UpFile.ApplicationDbContext db = new UpFile.ApplicationDbContext();
        private const string outFolder = "Output\\";
        private const string uploaded = "Uploaded\\";
        private string root = AppDomain.CurrentDomain.BaseDirectory;
        private List<Dictionary<string, string>> dictList = new List<Dictionary<string, string>>();
        private Doc globalDoc = new Doc();

        // GET: Docs
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Docs.ToList());
        }
        // Aðalfallið. Hér gerist galdurinn.
        [Authorize]
        public ActionResult Send(string rows)
        {
            string values;
            List<Device> devices;
            ProcessSendString(rows, out values, out devices);

            CompanyLicense companyLicense;
            UpFile devDownFile, up;
            List<string> excelFileNames;
            List<UpFile> outFilesToShow;
            Dictionary<string, string> dict;
            string fileName;
            UpFile wordFile;
            var valueDict = new Dictionary<string, Dictionary<string, string>>();
            StartExcel(rows, devices, out companyLicense, out devDownFile, out excelFileNames, out outFilesToShow, out dict, out fileName, out up, values, out wordFile, out valueDict);

            // End of Excel processing
            // ATHUGIÐ! /Output/ má ekki vera opið í Windows Explorer. Lokið því.
            // Annars kemur oft IOException. (að verið sé að nota skrána)

            // Begin Word processing
            StartWord(wordFile, companyLicense, devices, dict, valueDict, outFilesToShow);
            // End Word processing
            //db.SaveChanges();
            PrepareViewBag(devices, companyLicense, excelFileNames, wordFile);

            return PartialView("_SelectedRows", outFilesToShow);
        }

        // Word fallið, næsta stig fyrir neðan Send.
        private void StartWord(UpFile wordFile, CompanyLicense companyLicense, List<Device> devices, Dictionary<string, string>  dict, Dictionary<string, Dictionary<string, string>> valueDict, List<UpFile> outFilesToShow)
        {
            string src = InitializeWordObjects(wordFile, outFilesToShow);

            using (WordprocessingDocument wordDoc = WordprocessingDocument.Open(src, true))
            {
                Regex regexText = new Regex("");
                string regex = "";
                var el0 = dictList.ElementAt(0);
                string docText = GetText(wordDoc);

                docText = WriteAuthorLicense(ref docText, ref regexText, el0); 
                docText = WriteDeviceList(ref regex, ref docText);
                docText = WriteValues(valueDict, ref regexText, ref docText);

                /*
                var i = 0;
                var occurred = "";
                foreach (var entry in valueDict)
                {
                    if (entry.Key == "c8" || entry.Key == "c9" || entry.Key == "c10" || entry.Key == "v5")
                    {
                        occurred += entry.Key + ":" + entry.Value + ";";
                        i++;
                    }
                }
                Mælarnir. ( {{insertMetres}} í Skýrsla.docx ) 
                Hugmyndin var þessi: Þar sem notandinn velur mæla fyrir hvert tæki þá þarf að draga valda mæla upp úr öllum tækjunum.
                Ég ímyndaði mér streng sem innihéldi þetta allt saman. Svo bara prófarðu t.d.
                if occurred contains c8: write c8 to doc
                if occurred contains c9: write c9 to doc
                o.s.frv.
                */
                WriteToDoc(wordDoc, docText);
            }
        }
        // Word fall - skoðaðu Skýrlsa.docx fyrir nánari upplýsingar
        private string WriteValues(Dictionary<string, Dictionary<string, string>> valueDict, ref Regex regexText, ref string docText)
        {
            string paragraph = "";
            regexText = new Regex("{{insertDevices}}");
            var i = 1;
            string comments = "Athugasemdir: ";
            foreach (var entry in valueDict)
            {
                var sub = entry.Value;
                var devices = from d in db.Devices
                              where d.gre == entry.Key
                              select d;
                var device = devices.ToArray()[0];
                paragraph += "Tæki " + i++ + ": " + getDeviceValueWhere(device, "Framleiðandi") + " " + getDeviceValueWhere(device, "Tegund gerð") + " (" + entry.Key + ")" + "<w:br />"
                    + "Innstilltur geislunartími var " + sub["v25"] + " msek, en mældur tími (meðaltal) var " + sub["v22"] + " msek ";

                var fravik_timi = double.Parse(sub["v23"], CultureInfo.InvariantCulture);
                if (fravik_timi < 20) paragraph += "(frávik undir 20%).";
                else paragraph += "(frávik yfir 20%). *";

                paragraph += "<w:br />";

                paragraph += "Geislaskammtur á mynd mældist ";
                var skammtur = double.Parse(sub["v20"], CultureInfo.InvariantCulture);
                var hamark = double.Parse(sub["v26"], CultureInfo.InvariantCulture);
                if (skammtur > hamark) paragraph += skammtur + " mGy. *";
                else paragraph += skammtur + " mGy.";

                paragraph += " Leyfilegt hámark er " + sub["v26"] +" mGy á mynd.<w:br />"
                    + "Geislaskammtur á tímaeiningu mældist " + sub["v21"] + " mGy/s.<w:br />"
                    + "Innstillt spenna var " + sub["v24"] + " kV, en mæld spenna (meðaltal) var " + sub["v18"] + " kV ";

                var fravik_spenna = double.Parse(sub["v19"], CultureInfo.InvariantCulture);
                if (fravik_spenna < 10) paragraph += "(frávik undir 10%).";
                else paragraph += "(frávik yfir 10%). *";

                paragraph += "<w:br />";

                if (sub["v1"]!="") paragraph += "Notaður er " + sub["v1"] + " millisekúndna myndatökutími fyrir bitewing fullorðinna.<w:br />";
                if (sub["v2"]!="") paragraph += "Notaður er " + sub["v2"] + " millisekúndna myndatökutími fyrir bitewing barna.<w:br />";
                if (fravik_timi > 20) comments += "Frávik geislunartíma meira en 20%. ";
                if (fravik_spenna > 10) comments += "Frávik geislaskammts á tímaeiningu meira en 10%.";
                paragraph += comments;

                paragraph += "<w:br /><w:br />";
            }
            docText = regexText.Replace(docText, paragraph);
            return docText;
        }

        private string InitializeWordObjects(UpFile wordFile, List<UpFile> outFilesToShow)
        {
            string copied = CopyDownFile(wordFile, null, null);
            var src = root + outFolder + globalDoc.Malsnumer + "\\" + copied;
            var up = new UpFile
            {
                Name = copied,
                Date = DateTime.Now,
                Purpose = "out",
                FileType = ".docx",
                Malsnumer = globalDoc.Malsnumer,
                Size = wordFile.Size,
            };
            db.UpFiles.Add(up);
            db.SaveChanges();
            outFilesToShow.Add(up);
            return src;
        }

        // Aðeins fyrir prófun
        private static string el0Test(ref string regex, Dictionary<string, string> el0, ref string docText)
        {
            Regex regexText;
            foreach (var entry in el0)
            {
                regex += "- ";

                regex += entry.Key + " " + entry.Value;
                regex += "<w:br />";
            }
            regex = regex.Replace("{{", ";  ").Replace("}}", ": ");
            regexText = new Regex("{{el0_test}}");
            docText = regexText.Replace(docText, regex);
            return docText;
        }

        // Word fall
        private string WriteDeviceList(ref string regex, ref string docText)
        {
            Regex regexText;
            foreach (var subDict in dictList.Skip(1))
            {
                regex += "- ";

                foreach (KeyValuePair<string, string> entry in subDict)
                {
                    regex += entry.Key + " " + entry.Value;
                }
                regex += "<w:br />";
            }
            regex = regex.Replace("{{", ";  ").Replace("}}", ": ");
            regexText = new Regex("{{beginDevices}}");
            docText = regexText.Replace(docText, regex);
            return docText;
        }

        // Word fall
        private static string WriteAuthorLicense(ref string docText, ref Regex regexText, Dictionary<string, string> el0)
        {
            foreach (KeyValuePair<string, string> entry in el0)
            {
                /* Það er eitthvað skrýtið í gangi með þessa Replace skipun.
                 * Stundum hætta SUMIR reitir að virka. Það virðist hrífa að
                 * skrifa reitina inn handvirkt. Hvernig sem það virkar...
                 *
                 * Það virkar að eyða alveg út því sem þú ert búinn að gera --- MEÐ bilum og ÖLLU --- og gera þetta upp á nýtt með því að SKRIFA það inn, ekki afrita og líma.
                 * Það virðist vera brothætt að breyta því sem fyrir er.
                 * "Ástæðan" er sú að í Word XML-inu virðist sem breytunum sé skipt í hluta þ.a. XML-ið heldur t.d. að 

steer/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using steer.Models;
using LinqToExcel;

namespace steer.Controllers
{
    public class FilesController : Controller
    {
        private UpFile.ApplicationDbContext db = new UpFile.ApplicationDbContext();

        // GET: Files
        [Authorize]
        public ActionResult Index()
        {
            var fileList = from f in db.UpFiles
                           where f.Purpose != "out"
                           select f;
            return View(fileList);
        }


        // GET: Files/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            ViewBag.companies = db.CompanyLicenses.ToList();
            var companyDownFiles = from c in db.UpFiles
                                where c.Purpose == "company"
                                select c;
            ViewBag.companyDownFiles = companyDownFiles;
            var deviceDownFiles = from d in db.UpFiles
                                  where d.Purpose == "device"
                                  select d;
            ViewBag.deviceDownFiles = deviceDownFiles;
            var wordDownFiles = from w in db.UpFiles
                                where w.Purpose == "word"
                                select w;
            ViewBag.wordDownFiles = wordDownFiles;
            var authors = from a in db.Authors
                          select a;
            ViewBag.authors = authors;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UpFile upFile = db.UpFiles.Find(id);
            if (upFile == null)
            {
                return HttpNotFound();
            }

            return View(upFile);
        }

        // GET: Files/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Upload/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,FileType,Size")] UpFile upFile)
        {
            if (ModelState.IsValid)
            {
                db.UpFiles.Add(upFile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(upFile);
        }

        // GET: Files/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UpFile upFile = db.UpFiles.Find(id);
            if (upFile == null)
            {
                return HttpNotFound();
            }
            return View(upFile);
        }

        // POST: Files/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "ID,Name,FileType,Size")] UpFile upFile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(upFile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(upFile);
        }
        [Authorize]
        public ActionResult Generated()
        {
            var outFiles = from f in db.UpFiles
                           where f.Purpose == "out"
                           select f;
            return View(outFiles);
        }
        [Authorize]
        public ActionResult CL()
        {
            var CLFiles = from c in db.UpFiles
                          where c.Purpose == "company"
                          select c;
            return View(CLFiles);
        }
        [Authorize]
        public ActionResult Reports()
        {
            var reports = from r in db.UpFiles
                          where r.Purpose == "word"
                          select r;
            return View(reports);
        }
        [Authorize]
        public ActionResult Dev()
        {
            var devFiles = from d in db.UpFiles
                           where d.Purpose == "device"
                           select d;
            return View(devFiles);
        }

        // GET: File/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UpFile upFile = db.UpFiles.Find(id);
            if (upFile == null)
            {
                return HttpNotFound();
            }
            return View(upFile);
        }

        // POST: File/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            UpFile upFile = db.UpFiles.Find(id);
            db.UpFiles.Remove(upFile);
            string path = AppDomain.CurrentDomain.BaseDirectory + "Uploaded\\" + upFile.Name;
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

steer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <link rel="stylesheet" href="~/Content/fancy.css" />
    <script type="text/javascript" src="~/Content/fancy.js"></script>
    <link rel="stylesheet" href="~/Scripts/dataTables.bootstrap.min.css" />
    <link rel="stylesheet" href="~/Scripts/jquery.dataTables_themeroller.css" />
    <script type="text/javascript" src="~/Scripts/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Scripts/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/plug-ins/1.10.7/sorting/datetime-moment.js"></script>
    <script type="text/javascript" src="~/Scripts/date.js"></script>
    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"49147402-a14c-4e90-a86d-0c52054040c9"
        });
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div id="wrapper">
    <!--<div class="overlay"></div> Gerir hvítan, gegnsæjan lit á skjáinn þegar maður ýtir á takkann.  -->
        @if (Request.IsAuthenticated)
        {
            <!-- Sidebar -->
            <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
                <ul class="nav sidebar-nav">
                    <li class="sidebar-brand">
                        @Html.ActionLink("Stýrið", "Index", "Home", null, null)
                    </li>
                    <li>
                        @Html.ActionLink("Heim","Index","Home",null,null)
                    </li>
                    <li>
                        @Html.ActionLink("Excel skjöl","Index","Files",null,null)
                    </li>
                    <li>
                        @Html.ActionLink("Aðgerðaskrá","Index","Docs",null,null)
                    </li>
                    <li>
                        @Html.ActionLink("Leyfishafar","CL","Docs",null,null)
                    </li>
                    <li>
                        @Html.ActionLink("Leyfishafafyrirmyndir","CL","Files",null,null)
                    </li>
                    <li>
                        @Html.ActionLink("Tækjafyrirmyndir","Dev","Files",null,null)
                    </li>
                    <li>
                        @Html.ActionLink("Skýrslufyrirmyndir","Reports","Files",null,null)
                    </li>
                    <li>
                        @Html.ActionLink("Höfundar","Index","Authors",null,null)
                    </li>
                    <li>
                        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:document.getElementById('logoutForm').submit()">Útskrá @User.Identity.Name</a>
                        }
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                        <li class="dropdown-header">Dropdown heading</li>
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- /#sidebar-wrapper -->
        }
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                <span class="hamb-top"></span>
    			<span class="hamb-middle"></span>
				<span class="hamb-bottom"></span>
            </button>
            <div class="container" style="margin-top:-6em;">
                <div class="row">
                    <div class="col-lg-10 col-lg-offset-1">
                        <h1>@ViewBag.Title</h1>
                        <hr />
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        var table = $('table').DataTable({
            "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
        });
        $.extend($.fn.dataTableExt.oStdClasses, {
            "sWrapper": "dataTables_wrapper form-inline",
        });     
    </script>
</body>
</html>